config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :posts
  resources :comments

  root to: "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  
  validates :content, presence: true, length: {minimum:1, maximum:255}
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { minimum: 10 }
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true

    validates :email, presence: true, length: {minimum:4, maximum:255},
    format: { with: VALID_EMAIL_REGEX },
    uniqueness:  { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 8 }
    has_secure_password
    has_many :posts
    has_many :comments




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>All comments</h1>

<ul id="comments">
  <% @comments.each do |comment| %>
    <li>
      <%= link_to comment.content, comment_path(comment) %>
    </li>
  <% end %>
</ul>

<%= link_to "Go to Users", users_path %><br>
<%= link_to "Go to Posts", posts_path %>

app/views/comments/show.html.erb
<p>
  Author: <%= @comment.user.name  %>    
</p>
<p>
  Created: <%= @comment.created_at  %>    
</p>
<p>
  Updated: <%= @comment.updated_at  %>    
</p>

<p>
  Post: <%= @comment.post.title  %>    
</p>

<p><%= @comment.content %></p>

<%= link_to "<< Back to comments List", comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroReddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul id="posts">
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>

<%= link_to "Go to Users", users_path %><br>
<%= link_to "Go to Comments", comments_path %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
    <%= f.text_field :title %><br>
    <%= f.text_field :user_id %><br>
    <%= f.text_area :body, size: "60x12" %><br>
    <%= f.submit "Create" %>
  <% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
  Author: <%= @post.user.name  %>    
</p>
<p>
  Created: <%= @post.created_at  %>    
</p>
<p>
  Updated: <%= @post.updated_at  %>    
</p>

<p><%= @post.body %></p>

<%= link_to "<< Back to posts List", posts_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user) %>
    </li>
  <% end %>
</ul>


<%= link_to "Go to Posts", posts_path %>
<%= link_to "Go to Comments", comments_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>
  Posts:
  <ul>
  <% @user.posts.each do |post| %>
    <li> <%= link_to post.title, post_path(post) %></li>
  <% end %>
  </ul>
</p>
<p> E-mail: <%= @user.email %></p>



<%= link_to "<< Back to Users List", users_path %>